data:
  batch_size: 64
  val_batch_size: 64
  num_workers: 64 #10


  data_fn: "brain_lightsheet.{}.txt"
  data_dir: /data/jhahn/data/shape_dataset/pc_data/brain_lightsheet/train/
  data_val_dir: /data/jhahn/data/shape_dataset/pc_data/brain_lightsheet/val/
  mesh_data_dir: /data/jhahn/data/shape_dataset/data
  


  #data_fn: "shape.{}.txt"
  #data_dir: /data/jhahn/data/shape_dataset/pc_data/train/
  #data_val_dir: /data/jhahn/data/shape_dataset/pc_data/val/

  
  #data_fn: "brain.{}.txt"
  #data_dir: /data/jhahn/data/shape_dataset/pc_data/train/
  #data_val_dir: /data/jhahn/data/shape_dataset/pc_data/val/
  
  #data_fn: "brain_block.{}.txt"
  #data_dir: /data/jhahn/data/shape_dataset/pc_data/brain_block/train/
  #data_val_dir: /data/jhahn/data/shape_dataset/pc_data/brain_block/val/
  
  
  #data_fn: "tg.{}.txt"
  #data_dir: /data/jhahn/data/shape_dataset/pc_data/tg/train/
  #data_val_dir: /data/jhahn/data/shape_dataset/pc_data/tg/val/
  

  #data_fn: "everyday.{}.txt"
  #data_dir: /data/jhahn/data/breaking_bad/everyday/pc_data/train/
  #data_val_dir: /data/jhahn/data/breaking_bad/everyday/pc_data/val/
  


  rot_range: -1
  overfit: -1
  min_num_part: 2
  max_num_part: 20

